### ISSUE TITLE
Make Raster Output Filename a Variable

### ISSUE THREAD

**Issue by gbrunner** [edeeba13/final_prg_lake_IDW#4]
@edeeba13 Make the raster output from IDW a variable and put that towards the top of the code with other variables.

**Comment by edeeba13** [comment]
like, outIDW = Idw(inPointFeatures, zField)? I'm not sure what you mean by this, but I'm also attempting to finish this up with a fever so I could be misinterpreting you.

**Comment by gbrunner** [comment]
say like:
out_raster = "raster1.tif"
outIDW.save(out_raster)

**Comment by edeeba13** [comment]
Okay. Also, can i clip a tiff file? My interpolation is working but it is pretty low quality so I think changing the cell size for it and clipping it to a the lake.shp will clean it up.

**Comment by gbrunner** [comment]
Yes you can clip it. First though try setting your IDW to be
outIDW = Idw(inPointFeatures, zField) 
and see what the results look like (in case you haven't tried that yet).

**Comment by edeeba13** [comment]
I just pushed something up for you to look at. Thanks.

**Comment by gbrunner** [comment]
nice. is it working for you?

**Comment by edeeba13** [comment]
It doesn't like my shapefile. I uploaded it to github to see if you could
determine what it doesn't like about it.
Thanks for your help,
Emily

On Sun, Apr 30, 2017 at 4:15 PM, Gregory Brunner <notifications@github.com>
wrote:

> nice. is it working for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_edeeba13_final-5Fprg-5Flake-5FIDW_issues_4-23issuecomment-2D298257655&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=ewEOsibsNC_ANqQNo0hrdQ&m=Le5UVpHambSXzUJSm1kvGjk63wp9YcFDBVatAcPXQ8o&s=MTgR43wn9kg5mLRvple03giN7YpD0nFxjke4AsqiJTg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZV97lZCWd0vZhYDHQf3K8lIdqoX92Uiks5r1Pn5gaJpZM4NIRZ6&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=ewEOsibsNC_ANqQNo0hrdQ&m=Le5UVpHambSXzUJSm1kvGjk63wp9YcFDBVatAcPXQ8o&s=m2Akpl_LTW8ykMxMkC7gcFn9dZ2XgfnkudJhSP_T5Vs&e=>
> .
>



-- 
*Emily Deeba*
Student, Earth and Atmospheric Science
Saint Louis University

**Comment by gbrunner** [comment]
👍
